### ISSUE TITLE
Call to undefined method Akaunting\Module\Facade::isDeferred()

### ISSUE THREAD

**Issue by hemendraajmera** [akaunting/module#3]
Call to undefined method Akaunting\Module\Facade::isDeferred() 
after using module module in application

**Comment by denisdulici** [comment]
Where do you exactly call that method?

**Comment by hemendraajmera** [comment]
I am also facing issue on menu module 
 Call to undefined method Akaunting\Menu\Facade::isDeferred()

![Uploading image.png…]()

**Comment by hemendraajmera** [comment]
![image](https://user-images.githubusercontent.com/2478037/81564606-a08a4000-93b5-11ea-8e85-720287e913fc.png)

**Comment by denisdulici** [comment]
Thap happens when you put the facade in providers list:

https://laracasts.com/discuss/channels/laravel/call-to-undefined-method-barryvdhdebugbarfacadeisdeferred
